{% set name = "nannyml" %}
{% set version = "0.12.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/NannyML/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 67801824c003ec37b055a6c0f4d540e20d3eff8f84cb6e202a40d2b349c092df

build:
  number: 0
  entry_points:
    - nannyml=nannyml.cli.cli:cli
    - nml=nannyml.cli.cli:cli
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  # https://github.com/NannyML/nannyml/blob/v0.12.1/pyproject.toml#L33
  skip: True  # [py<38 or py>311]
  # nothing provides requested flaml >=1.0.11,<2.0 on s390x
  # nothing provides requested python-kaleido 0.2.1.* on s390x
  skip: True  # [s390x]

requirements:
  host:
    - pip
    - poetry-core >=1.0.0
    - python
  run:
    - python
    - pandas >=1.5,<2
    - python-dateutil >=2.8.2,<3.0.0
    - scikit-learn >=1.2,<2.0
    - joblib >=1.1.0,<2.0
    - category_encoders >=2.3.0,<3.0.0
    - matplotlib-base >=3.7,<4.0
    - plotly >=5.6.0,<6.0
    - scipy >=1.10,<2.0
    - numpy >=1.24,<1.25
    - seaborn >=0.13.2,<1.0
    # kaleido same as python-kaleido
    - python-kaleido ==0.2.1
    - pyarrow >=14.0.0,<15.0.0
    - gcsfs >=2022.5.0
    - pydantic >=2.7.4,<3.0.0
    - rich >=12.5.1
    - click >=8.1.3,<9.0.0
    - pyyaml >=6.0,<7.0
    - jinja2 <3.1
    - pyfiglet >=0.8.post1,<1.0
    - lightgbm >=3.3.2,<4.0
    - flaml >=1.0.11,<2.0
    - s3fs >=2022.8.2
    - apscheduler >=3.9.1,<4.0
    - analytics-python >=2.3.2,<3.0
    - python-dotenv >=0.21.0,<1.0
    - types-pyyaml >=6.0.12.8,<7.0
    - types-python-dateutil >=2.8.19.10,<3.0
  run_constrainted:
    - sqlmodel >=0.0.19,<0.1.0
    # psycopg2 on defaults is basically psycopg2-binary (without the bundled/vendored dependencies)
    - psycopg2 >=2.9.3,<3

test:
  source_files:
    - tests
  imports:
    - nannyml
  commands:
    - pip check
    - nannyml --help
    - nml --help
    # Disable tests only on osx-64 (Seg Faults in random places)
    #Fatal Python error: Segmentation fault
    #Thread 0x000000010b16be00 (most recent call first):
    #File "/var/folders/sy/f16zz6x50xz3113nwtb9bvq00000gp/T/abs_cdtuv5r_1z/croot/nannyml_1736512349061/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_p/lib/python3.10/site-packages/lightgbm/basic.py", line 1659 in __init_from_np2d
    #File "/var/folders/sy/f16zz6x50xz3113nwtb9bvq00000gp/T/abs_cdtuv5r_1z/croot/nannyml_1736512349061/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_p/lib/python3.10/site-packages/lightgbm/basic.py", line 1538 in _lazy_init
    - pytest -v tests  # [not osx-64]
  requires:
    - pip
    - pytest >=6.2.4,<7
    - pytest-mock >=3.7.0,<4.0
    - pytest-lazy-fixture >=0.6.3,<1.0

about:
  home: https://github.com/nannyml/nannyml
  doc_url: https://nannyml.readthedocs.io/en/stable/
  summary: NannyML, Your library for monitoring model performance.
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  doc_url: https://www.nannyml.com/
  dev_url: https://github.com/nannyml/nannyml/
  description: NannyML is an open-source python library that allows you to estimate post-deployment model performance (without access to targets), detect data drift, and intelligently link data drift alerts back to changes in model performance.

extra:
  recipe-maintainers:
    - nnansters
    - thewchan
