{% set name = "nannyml" %}
{% set version = "0.12.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  #url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/nannyml-{{ version }}.tar.gz
  #sha256: db0e4a688d9d830ad3c461106f42335588ee03241f16a00fde00767b408ef704
  url: https://github.com/NannyML/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 67801824c003ec37b055a6c0f4d540e20d3eff8f84cb6e202a40d2b349c092df

build:
  number: 0
  entry_points:
    - nannyml=nannyml.cli.cli:cli
    - nml=nannyml.cli.cli:cli
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  skip: True  # [ py<38 or py>311]

requirements:
  host:
    - pip
    - poetry-core >=1.0.0
    - python
  run:
    - python
    - pandas >=1.5,<1.6
    - python-dateutil >=2.8.2,<2.9
    - scikit-learn >=1.2,<1.3
    - joblib >=1.1.0,<1.2
    - category-encoders >=2.3.0,<2.4
    - matplotlib >=3.7,<3.8
    - plotly >=5.6.0,<5.7
    - scipy >=1.10,<1.11
    - numpy >=1.24,<1.25
    - seaborn >=0.13.2,<0.14
    - kaleido ==0.2.1
    - pyarrow >=14.0.0,<15
    - gcsfs >=2022.5.0,<2025
    - pydantic >=2.7.4,<2.8
    - rich >=12.5.1,<12.6
    - click >=8.1.3,<8.2
    - pyyaml >=6.0,<7
    - jinja2 <3.1
    - pyfiglet >=0.8.post1,<0.9
    - lightgbm >=3.3.2,<3.4
    - flaml >=1.0.11,<1.1
    - s3fs >=2022.8.2,<2025
    - apscheduler >=3.9.1,<3.10
    - segment-analytics-python >=2.3.2,2.4
    - python-dotenv >=0.21.0,<0.22
    - types-pyyaml >=6.0.12.8,<6.0.13
    - types-python-dateutil >=2.8.19.10,<2.10

test:
  source_files:
    - tests
  imports:
    - nannyml
  commands:
    - pip check
    - nannyml --help
    - nml --help
    - pytest -v tests
  requires:
    - pip
    - pytest

#black = "^22.3.0"
#isort = "^5.8.0"
#flake8 = "^3.9.2"
#flake8-docstrings = "^1.6.0"
#flake8-typing-imports = "^1.12.0"
#mypy = "^1.0"
#pytest = "^6.2.4"
#pytest-cov = "^2.12.0"
#pytest-mock = "^3.7.0"
#tox = "^3.20.1"
#virtualenv = "^20.2.2"
#pip = ">=20.3.1,<22.0.0"
#twine = "^3.3.0"
#pre-commit = "^2.12.0"
#toml = "^0.10.2"
#bump2version = "^1.0.1"
#jupyterlab = "^3.2.9"
#sphinx = "^5.0.2"
#sphinx-rtd-theme = "^1.0.0"
#sphinx-toggleprompt = "^0.2.0"
#sphinx-copybutton = "^0.5.0"
#typing-extensions = "^4.4.0"
#sphinx-toolbox = "^3.2.0"
#pytest-lazy-fixture = "^0.6.3"
#types-click = "^7.1.8"
#types-python-dateutil = "^2.8.19.6"
#types-PyYAML = "^6.0"
#types-requests = "^2.31.0.3"   

about:
  home: https://github.com/nannyml/nannyml
  doc_url: https://nannyml.readthedocs.io/en/stable/
  summary: NannyML, Your library for monitoring model performance.
  license: Apache-2.0
  license_file: LICENSE
  doc_url: https://www.nannyml.com/
  dev_url: https://github.com/nannyml/nannyml/
  description: NannyML is an open-source python library that allows you to estimate post-deployment model performance (without access to targets), detect data drift, and intelligently link data drift alerts back to changes in model performance.

extra:
  recipe-maintainers:
    - nnansters
    - thewchan
